"""Auto-generate Claude Code hooks from repo config.

Generates .claude/settings.json and hook scripts matching the repo
enforcement level:

- strict: PreToolUse hooks blocking git push to protected branches
  and gh pr merge --auto, plus PostToolUse formatting hooks
- relaxed: PostToolUse formatting hooks only

Hook generation is deterministic and idempotent — same input always
produces the same output, and running twice has no additional effect.

Usage:
    from corc.hook_gen import generate_settings, sync_hooks

    # Generate settings dict (for inspection/testing)
    settings = generate_settings("strict", ["main", "staging"])

    # Write hooks to a repo's .claude/ directory
    written = sync_hooks("/path/to/repo", {
        "enforcement_level": "strict",
        "protected_branches": ["main", "staging"],
        "merge_policy": "human-only",
    })
"""

from __future__ import annotations

import json
from pathlib import Path


# ---------------------------------------------------------------------------
# Settings generation
# ---------------------------------------------------------------------------


def generate_settings(
    enforcement_level: str,
    protected_branches: list[str] | None = None,
    merge_policy: str = "auto",
) -> dict:
    """Generate .claude/settings.json content for a repo.

    Args:
        enforcement_level: 'strict' or 'relaxed'.
        protected_branches: List of protected branch names.
        merge_policy: 'auto' or 'human-only'.

    Returns:
        Dict representing the .claude/settings.json content.
    """
    if protected_branches is None:
        protected_branches = ["main"]

    hooks: dict[str, list] = {}

    # Strict enforcement: add PreToolUse hooks to block dangerous operations
    if enforcement_level == "strict":
        hooks["PreToolUse"] = [
            {
                "matcher": "Bash",
                "hooks": [
                    {
                        "type": "command",
                        "command": ".claude/hooks/enforce-policy.sh",
                    }
                ],
            }
        ]

    # Both strict and relaxed: add PostToolUse formatting hooks
    hooks["PostToolUse"] = [
        {
            "matcher": "Write|Edit",
            "hooks": [
                {
                    "type": "command",
                    "command": ".claude/hooks/format-python.sh",
                }
            ],
        }
    ]

    return {"hooks": hooks}


# ---------------------------------------------------------------------------
# Hook script templates
# ---------------------------------------------------------------------------

# Template for enforce-policy.sh (PreToolUse hook for strict repos).
# Uses raw string so backslashes are literal (needed for grep regex \s
# and bash line continuation \).
# __BRANCHES_PLACEHOLDER__ is replaced with the generated branches array.
_ENFORCE_POLICY_TEMPLATE = r"""#!/usr/bin/env bash
# PreToolUse hook: enforce repo merge policy.
# Blocks git push to protected branches and gh pr merge --auto.
# Generated by corc — do not edit manually.
set -euo pipefail

INPUT=$(cat)
COMMAND=$(printf '%s' "$INPUT" | jq -r '.tool_input.command // empty')

if [ -z "$COMMAND" ]; then
  exit 0
fi

# --- Block direct push to protected branches ---
PROTECTED_BRANCHES=(__BRANCHES_PLACEHOLDER__)

if printf '%s' "$COMMAND" | grep -qE 'git\s+push'; then
  for branch in "${PROTECTED_BRANCHES[@]}"; do
    if printf '%s' "$COMMAND" | grep -qE "(^|\s)${branch}(\s|$)|:${branch}(\s|$)"; then
      echo "BLOCKED: Direct push to protected branch '${branch}' is not allowed by repo policy."
      exit 2
    fi
  done
fi

# --- Block auto-merge ---
if printf '%s' "$COMMAND" | grep -qE 'gh\s+pr\s+merge' && \
   printf '%s' "$COMMAND" | grep -qF -- '--auto'; then
  echo "BLOCKED: Auto-merge (gh pr merge --auto) is not allowed by repo policy."
  exit 2
fi

exit 0
"""

_FORMAT_PYTHON_TEMPLATE = r"""#!/usr/bin/env bash
# PostToolUse hook: auto-format Python files with ruff after Write/Edit.
# Receives JSON on stdin from Claude Code with tool_input.file_path.
# Generated by corc — do not edit manually.
set -euo pipefail

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

# Only format Python files.
if [[ "$FILE_PATH" != *.py ]]; then
  exit 0
fi

# Only format if the file still exists.
if [ ! -f "$FILE_PATH" ]; then
  exit 0
fi

# Run ruff format. If ruff is not installed, skip gracefully.
if command -v ruff &>/dev/null; then
  ruff format "$FILE_PATH" 2>/dev/null || true
else
  python3 -m ruff format "$FILE_PATH" 2>/dev/null || true
fi

exit 0
"""


# ---------------------------------------------------------------------------
# Script generation
# ---------------------------------------------------------------------------


def generate_enforce_policy_script(protected_branches: list[str]) -> str:
    """Generate the enforce-policy.sh hook script content.

    The script blocks:
    - git push to any protected branch (by name or refspec)
    - gh pr merge --auto

    Branches are sorted for deterministic output.

    Args:
        protected_branches: List of protected branch names.

    Returns:
        Shell script content as a string.
    """
    branches = sorted(protected_branches)
    branches_str = " ".join(f'"{b}"' for b in branches)
    return _ENFORCE_POLICY_TEMPLATE.replace("__BRANCHES_PLACEHOLDER__", branches_str)


def generate_format_script() -> str:
    """Generate the format-python.sh hook script content.

    Returns:
        Shell script content as a string.
    """
    return _FORMAT_PYTHON_TEMPLATE


# ---------------------------------------------------------------------------
# Sync hooks to disk
# ---------------------------------------------------------------------------


def sync_hooks(repo_path: str, repo_config: dict) -> list[str]:
    """Write generated hooks to a repo's .claude/ directory.

    Generates .claude/settings.json and hook scripts based on the repo's
    enforcement level. Creates .claude/ and .claude/hooks/ directories
    if they don't exist.

    This function is idempotent — calling it twice with the same input
    produces identical files.

    Args:
        repo_path: Filesystem path to the repository root.
        repo_config: Repo configuration dict with keys:
            - enforcement_level: 'strict' or 'relaxed'
            - protected_branches: list of branch names
            - merge_policy: 'auto' or 'human-only'

    Returns:
        List of absolute file paths that were written.
    """
    enforcement_level = repo_config.get("enforcement_level", "strict")
    protected_branches = repo_config.get("protected_branches", ["main"])
    merge_policy = repo_config.get("merge_policy", "auto")

    repo_root = Path(repo_path)
    claude_dir = repo_root / ".claude"
    hooks_dir = claude_dir / "hooks"

    claude_dir.mkdir(parents=True, exist_ok=True)
    hooks_dir.mkdir(parents=True, exist_ok=True)

    written: list[str] = []

    # Generate .claude/settings.json
    settings = generate_settings(enforcement_level, protected_branches, merge_policy)
    settings_path = claude_dir / "settings.json"
    settings_content = json.dumps(settings, indent=2) + "\n"
    settings_path.write_text(settings_content)
    written.append(str(settings_path))

    # Generate .claude/hooks/format-python.sh (both strict and relaxed)
    format_script = generate_format_script()
    format_path = hooks_dir / "format-python.sh"
    format_path.write_text(format_script)
    format_path.chmod(0o755)
    written.append(str(format_path))

    # Generate .claude/hooks/enforce-policy.sh (strict only)
    if enforcement_level == "strict":
        enforce_script = generate_enforce_policy_script(protected_branches)
        enforce_path = hooks_dir / "enforce-policy.sh"
        enforce_path.write_text(enforce_script)
        enforce_path.chmod(0o755)
        written.append(str(enforce_path))

    return written
